services:

  mysql_db:
    image: "mysql:9"
    restart: unless-stopped
    container_name: ${PROJECT_NAME}-xwiki-mysql-db
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
    command:
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_bin"
      - "--explicit-defaults-for-timestamp=1"
    networks:
      - xwiki-internal

  xwiki_web_app:
    image: "xwiki:${XWIKI_VERSION}-mysql-tomcat"
    restart: unless-stopped
    container_name: ${PROJECT_NAME}-xwiki-mysql-tomcat-web
    depends_on:
      - mysql_db
    ports:
      - "${APP_PORT}:8080"
    environment:
      - XWIKI_VERSION=${XWIKI_VERSION}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - DB_HOST=mysql_db
      - JVM_OPTS=-Xms512m -Xmx1024m
    volumes:
      - xwiki-data:/usr/local/xwiki
    networks:
      - xwiki-internal
      - reverse-proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${PROJECT_NAME}-xwiki.entrypoints=https"
      - "traefik.http.routers.${PROJECT_NAME}-xwiki.rule=Host(`${APP_URL}`)"
      - "traefik.http.routers.${PROJECT_NAME}-xwiki.tls=true"
      - "traefik.http.routers.${PROJECT_NAME}-xwiki.tls.certresolver=${CERT_RESOLVER}"
      - "traefik.http.services.${PROJECT_NAME}-xwiki.loadbalancer.server.scheme=http"
      - "traefik.http.services.${PROJECT_NAME}-xwiki.loadbalancer.server.port=8080"

volumes:
  mysql-data:
    name: ${PROJECT_NAME}-mysql-data
    external: true

  xwiki-data:
    name: ${PROJECT_NAME}-xwiki-data
    external: true

networks:
  xwiki-internal:
    driver: bridge
    name: ${PROJECT_NAME}-xwiki-internal

  reverse-proxy:
    external: true
