General:
  RefreshAlbumPeopleInterval: ${REFRESH_ALBUM_PEOPLE_INTERVAL}
  PhotoDateFormat: "${PHOTO_DATE_FORMAT}"
  ImageLocationFormat: "${IMAGE_LOCATION_FORMAT}"
  WeatherApiKey: "${WEATHER_API_KEY}"
  UnitSystem: "${UNIT_SYSTEM}"
  WeatherLatLong: "${WEATHER_LAT_LONG}"
  Language: "${LANGUAGE}"
  Interval: ${INTERVAL}
  TransitionDuration: ${TRANSITION_DURATION}
  ShowClock: ${SHOW_CLOCK}
  ClockFormat: "${CLOCK_FORMAT}"
  ClockDateFormat: "${CLOCK_DATE_FORMAT}"
  ShowProgressBar: ${SHOW_PROGRESS_BAR}
  ShowPhotoDate: ${SHOW_PHOTO_DATE}
  ShowImageDesc: ${SHOW_IMAGE_DESC}
  ShowPeopleDesc: ${SHOW_PEOPLE_DESC}
  ShowAlbumName: ${SHOW_ALBUM_NAME}
  ShowImageLocation: ${SHOW_IMAGE_LOCATION}
  ShowWeatherDescription: ${SHOW_WEATHER_DESCRIPTION}
  WeatherIconUrl: "${WEATHER_ICON_URL}"
  ImageZoom: ${IMAGE_ZOOM}
  ImagePan: ${IMAGE_PAN}
  ImageFill: ${IMAGE_FILL}
  Layout: "${LAYOUT}"

Accounts:
  - ImmichServerUrl: "${IMMICH_SERVER_URL}"
    ApiKey: "${IMMICH_API_KEY}"
    ImagesFromDate: ${IMAGES_FROM_DATE}
    ShowMemories: ${SHOW_MEMORIES}
    ShowFavorites: ${SHOW_FAVORITES}
    ShowArchived: ${SHOW_ARCHIVED}
    ImagesFromDays: ${IMAGES_FROM_DAYS}
    Rating: ${RATING}

    Albums:
      - "${ALBUM_ID}"
