
services:
  stirling-pdf:
    image: stirlingtools/stirling-pdf:latest
    container_name: stirling-pdf
    env_file:
      - .env
    networks:
      - reverse-proxy
    ports:
      - '${APP_PORT}:8080'
    volumes:
      - data:/configs
    restart: unless-stopped

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pdf.rule=Host(`${APP_URL}`)"
      - "traefik.http.routers.pdf.tls=true"
      - "traefik.http.routers.pdf.tls.certresolver=${CERT_RESOLVER}"
      - "traefik.http.services.pdf.loadbalancer.server.scheme=http"
      - "traefik.http.services.pdf.loadbalancer.server.port=${APP_PORT}"
      - "traefik.http.routers.pdf.entrypoints=https"

networks:
  reverse-proxy:
    external: true
volumes:
  data: